name: Pipeline CI/CD

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - users: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      
      run: npm install
      run: npm test
    
    deploy:
      needs: build
      runs-on: ububtu-latest
      steps:
        - name: Deploy (Simulado)
          run: echo "Deploy realizado com sucesso!"
